spring:
  datasource:
    username: root
    password: Zh1314520.
    url: jdbc:mysql://121.5.114.159:3306/tmall?serverTimezone=UTC&&useSSL=false
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  #在建表的时候，将默认的存储引擎切换为 InnoDB
  database-platform: org.hibernate.dialect.MySQL8Dialect
  # 配置在日志中打印出执行的 SQL 语句信息。
  show-sql: true
  hibernate:
    ddl-auto: update
